### ISSUE TITLE
I'm pretty confident that Windows PowerShell (v5) is not getting any more updates, but PowerShell Core is, so you might be able to ask them. Or even add it by default to [PsReadline](https://github.com/PowerShell/PSReadLine/issues), which handles many of the niceties of the PS prompt. We can't do anymore on our side; we need to let the shell tell us what the path is.1027936274_

### ISSUE THREAD

**Issue by VSIM132** [vincentsimard/vsimbot#14]
I'm pretty confident that Windows PowerShell (v5) is not getting any more updates, but PowerShell Core is, so you might be able to ask them. Or even add it by default to [PsReadline](https://github.com/PowerShell/PSReadLine/issues), which handles many of the niceties of the PS prompt. We can't do anymore on our side; we need to let the shell tell us what the path is. 

_Originally posted by @zadjii-msft in https://github.com/microsoft/terminal/issues/12331#issuecomment-1027936274_

**Comment by vincentsimard** [comment]
Cool story
